trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.11'
    addToPath: true
    architecture: 'x64'
  displayName: 'Usa Python 3.11'

- task: Cache@2
  inputs:
    key: 'venv'
    path: /home/vsts/work/venv
    restoreKeys: venv
  displayName: 'Cache del virtual enviroment'

- script: |
    if [ ! -d "/home/vsts/work/venv" ]; then
      python -m venv /home/vsts/work/venv
    fi
  displayName: 'Attivazione del virtual enviroment per Python'

- script: |
    source /home/vsts/work/venv/bin/activate
    pip install --break-system-packages testzeus-hercules
    pip install --upgrade --break-system-packages ag2[openai] openai
  displayName: 'Install Testzeus Hercules dependencies'

- script: |
    source /home/vsts/work/venv/bin/activate
    pip install --break-system-packages playwright
    playwright install --with-deps
  displayName: 'Installa Playwright'

- script: |
    source .env
    source /home/vsts/work/venv/bin/activate
    sed -i "s/\[API-KEY\]/$(API_KEY)/g" agents_llm_config.json
    testzeus-hercules
  displayName: 'Esegui Testzeus Hercules'